version: '3.7'

services:
  consul-agent-1: &consul-agent
    image: consul:latest
    restart: always
    networks:
      - silky_service_net
    command: "agent -retry-join consul -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server
    ports:
      - "8501:8500"
    command: "agent -server -retry-join consul -client 0.0.0.0 -ui"

  consul-server-3:
    <<: *consul-server
    ports:
      - "8502:8500"
    command: "agent -server -retry-join consul -client 0.0.0.0 -ui"

  consul:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  silky_service_net:
    external:
      name: silky_service_net